### PR TITLE
Drop support for armv7hf sid base images

### PR DESCRIPTION
**Pull request by nghiant2710**

### CODE REVIEW

**Comment by nghiant2710** [comment]
@petrosagg please review this PR

**Comment by petrosagg** [comment]
@nghiant2710 this has conflicts. Why are we dropping sid?

**Comment by nghiant2710** [comment]
@petrosagg I will resolve it later but I think we can drop sid since it's quite old, not sure if any users're using it. Sometimes, its repository mirrors are not reachable and our build jobs fail for it

**Comment by petrosagg** [comment]
sid is not old at all. It is the unstable version of Debian and has all the latest packages

**Comment by nghiant2710** [comment]
ok, I will close this PR

**Pull request closed without merging**
