### PR TITLE
Stop installing systemd on wheezy images

### PR DESCRIPTION
**Pull request by nghiant2710**

### CODE REVIEW

**Comment by nghiant2710** [comment]
@Page- , can you review this PR please?

**Comment by Page-** [comment]
Why is this necessary?

**Comment by nghiant2710** [comment]
@Page- http://jenkins.dev.resin.io/view/Resin%20Library/job/resin-beaglebone-buildpack-deps/ws/bashbrew/logs/build-2015-07-23--18-52-13/build-beaglebone-buildpack-deps%3Awheezy.log/*view*/

Installing systemd from backports also installs some dependencies from backports which causes unmet dependencies when installing new packages. we've agreed that if systemd doesn't play well on wheezy then we can drop it. Hence, it's better to remove it from wheezy

**Comment by Page-** [comment]
Ok, if @petrosagg wants to look into this further it'd be easy enough to revert this and do the steps to fix it

**Pull request merged**
