### PR TITLE
Add VersionBot changes to repository (Autogenerate changelog only)

### PR DESCRIPTION
**Pull request by nghiant2710**
Change-Type: patch

### CODE REVIEW

**Comment by nghiant2710** [comment]
@hedss, can you review this PR and enable version bot for this repo please?

**Comment by hedss** [comment]
@nghiant2710 Sure. One question, where did the `versionist` config for this come from? It looks like it's missing some options.

**Comment by nghiant2710** [comment]
@hedss, I made this config file myself, basically I only want it to automatically update the changelog since we don't use version for this repo so please fix me if i'm wrong.

**Comment by hedss** [comment]
@nghiant2710 It's missing some of the code used for checking tags. Several repos use a config that only updates Changelogs. You should be able to use https://github.com/resin-io/resin-router-service/blob/master/versionist.conf.js and just drop it in instead! :)

**Comment by nghiant2710** [comment]
@hedss thanks. I made a small change in the template (version removed) since we dont need it here.

**Pull request merged**
