### PR TITLE
Set hostname to <device-type>-<device uuid> and update wrong link

### PR DESCRIPTION
**Pull request by nghiant2710**

### CODE REVIEW

**Comment by shaunmulligan** [comment]
LGTM, and sorry for not pinging you about changing the structure of the docs and breaking links, my bad :/

**Comment by shaunmulligan** [comment]
the better way would be to use %%RESIN_MACHINE_NAME%% but that would require switching to dockerfile.template and not sure if we want that or if it would cause problems?

**Comment by nghiant2710** [comment]
entry.sh script will be called on device so I don't think we have %%RESIN_MACHINE_NAME%% available

**Comment by shaunmulligan** [comment]
sorry what i meant was you could set ENV deviceName = %%RESIN_MACHINE_TYPE%%, this would work at least until we add device_name and other Resin variables to the device

**Comment by nghiant2710** [comment]
oh yes, makes sense

**Comment by shaunmulligan** [comment]
Are there any obvious issues with switching to dockerfile.template and doing it this way @nghiant2710 and @petrosagg ?

**Pull request closed without merging**
