### PR TITLE
Fix #52. Systemd booting logs issue.

### LINKED ISSUE #52: systemd booting logs are showed on resin dashboard logs

### PR DESCRIPTION
**Pull request by nghiant2710**

### CODE REVIEW

**Comment by shaunmulligan** [comment]
it may be cool to make this user settable, so it is by default off, but if a user wants they can set and env var and then the systemd logs will be shown...just an idea

**Comment by nghiant2710** [comment]
@shaunmulligan, I don't think we should let user do that since these logs are not useful for users. They can retrieve logs for each service using `journalctl`

**Comment by shaunmulligan** [comment]
They may be useful, one could see if devices are being plugged in correctly or if a service is starting up and failing etc. But i guess it is possible through journalctl, i guess maybe @petrosagg might have some feelings on this

**Comment by petrosagg** [comment]
I don't mind either way. SGTM

**Pull request merged**
